# Generated by Django 4.2.2 on 2023-12-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="move",
            field=models.CharField(
                default="1*,2*,3*,4*,5*,6*,7*,8*,9*", max_length=100
            ),
        ),
    ]
