# Generated by Django 4.2.2 on 2023-12-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1", models.CharField(max_length=100)),
                ("player2", models.CharField(max_length=100)),
                ("decision", models.BooleanField(null=True)),
            ],
        ),
    ]
