# Generated by Django 4.2.2 on 2023-12-04 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challenge",
            old_name="player1",
            new_name="challenger",
        ),
        migrations.RenameField(
            model_name="challenge",
            old_name="player2",
            new_name="opponent",
        ),
    ]
